#!/bin/bash

rm spheredp
rm *.dat
rm *.png
gcc  -o spheredp spheredp.c -O3 -lm
./spheredp << EOF
.2
10
5
200
1
1
1
0.5
$RANDOM
EOF

gnuplot <<EOF
	set autoscale
	unset log
	unset label
	set xtic auto				  
	set ytic auto
	set title "Error propagation over time"
	set xlabel "Time"
	set ylabel "Field mean value"
	set term png crop medium size 1200,800
	set out 'hi.png'
	plot    "hi.dat" u 1:2 title 'c0' with linespoints
	unset log
	unset label
	set xtic auto				  
	set ytic auto
	set title "DD over time"
	set xlabel "Time"
	set ylabel "DD"
	set term png crop medium size 1200,800
	set out 'hi2.png'
	plot    "hi.dat" u 1:3 title 'DD(phi,Ntheta,Nphi)' with linespoints
EOF
nohup eog hi.png  &>/dev/null &
wmctrl -r "hi.png" -b toggle,above 
nohup eog hi2.png  &>/dev/null &
wmctrl -r "hi2.png" -b toggle,above 
#cat hi.dat








